# Generated by Django 4.1.7 on 2023-03-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('bio', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=250, null=True)),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ArtSubRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_created_mediums', to='artseenapi.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=500, null=True)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=1000)),
                ('available_purchase', models.BooleanField(default=False)),
                ('available_show', models.BooleanField(default=False)),
                ('will_ship', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=True)),
                ('quantity_available', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artseenapi.artist')),
                ('arttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arttype_pieces', to='artseenapi.arttype')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_using_this_media', to='artseenapi.media')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_created_surfaces', to='artseenapi.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PieceSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_with_subtype', to='artseenapi.piece')),
                ('subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes_of_a_piece', to='artseenapi.subtype')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='subtypes',
            field=models.ManyToManyField(related_name='subtype_pieces', through='artseenapi.PieceSubType', to='artseenapi.subtype'),
        ),
        migrations.AddField(
            model_name='piece',
            name='surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_using_this_surface', to='artseenapi.surface'),
        ),
        migrations.AddField(
            model_name='arttype',
            name='subtypes',
            field=models.ManyToManyField(related_name='subtypes_of_arttype', through='artseenapi.ArtSubRelationship', to='artseenapi.subtype'),
        ),
        migrations.AddField(
            model_name='artsubrelationship',
            name='arttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artseenapi.arttype'),
        ),
        migrations.AddField(
            model_name='artsubrelationship',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artseenapi.subtype'),
        ),
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_in_the_city', to='artseenapi.city'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
